### ISSUE TITLE
Hard coded names in the template

### ISSUE THREAD

**Issue by Zarquan** [stvoutsin/firethorn-utils#1]
The `configurator.load_jdbc_resource` method looks for hard coded names in the template, `{datauser}`, `{datapass}`, `{datahost}` etc. and replaces them with values from hard coded environment variables `datauser`, `datapass`, `datahost` etc. 

This works as long as we only ever want to load one JdbcResource.

If we want to load more than one JdbcResource, then we will need to use a different set of environment variables for the second, third and fourth JdbcResources.

Suggest that rather than looking for hard coded names in the template, the configurator should look for anything in curly brackets, and then use that as the name of the environment variable.

For example, if the JSON file for ATLASDR3 contained the following:

    "datauser": "{ATLASDR3user}",
    "datapass": "{ATLASDR3pass}",

Then the configurator should replace these with the values of the corresponding ATLASDR3user and ATLASDR3pass environment variables.

This would enable us to process more than one JdbcResource in a JSON file, and more than one JSON configuration file in the same deployment.

**Comment by stvoutsin** [comment]
Should be fixed in Commit:
 https://github.com/stvoutsin/firethorn-utils/commit/69ce49331d0b1944c18f85c5b37a67f0aa174b46
